### PR TITLE
[graphql] fix API generation fails if schema self-referencing types #1482

### PR DESCRIPTION
**Pull request by relefant**
Bug occurs when a schema has a parent type containing an array of references which reference a union containing the parent type.

In generating the union type, the parent type is recursed into - and this ends in an infinite loop.

My fix is to put a recursion guard in `getUnionDefinition()` which checks for the same parent type occuring during recursion, and if this happens then bail out of the recursion. This should not affect the generation of the union type itself, and the recursion path is calculating child types which are not required for the union type generation in any case.

You probably want to test this code.

### CODE REVIEW

**Comment by kmelve** [comment]
Thanks for this! We will review it after the weekend 👍

**Comment by rexxars** [comment]
Thanks a bunch for this, very appreciated!

I discovered that the fix only worked for one level of depth - if you have a Post which can reference a Post/Category, and Category can reference a Post/Author, you would still get the recursion error.

Added a small change which uses an array as the guard and pushes/splices from the guard array when it completes one level. Does that look right to you?

Sorry about the force-pushing to your branch, we had some major changes done to our repo and I needed to rebase your fix.

**Comment by relefant** [comment]
Looks good to me. I neglected the case of more than one union in the hierarchy ;)
How do you test the schema generation?

**Comment by rexxars** [comment]
Unfortunately we don't yet have tests for the generation of these schemas. They are however verified on the server side. I assume you got the CLI running in development mode and was able to deploy?

**Pull request merged**
