### PR TITLE
Configurable ace modes

### PR DESCRIPTION
**Pull request by bjoerge**
### Description

People (understandably) want @sanity/code-input to support more languages (see #3036, #2357, #2682, #2264). However, enabling a language by default increases the bundle size even if the language is not used.

This PR adds support for configuring additional language support from the host studio application (see readme for an example).

Edit: oh, and while I was at it I upgraded react-ace to latest and removed brace in favor of ace-builds (official builds).

### What to review
See that the change makes sense and think of any potential problems with this approach that I didn't anticipate.

### Notes for release

- Allow configuring support for additional languages in @sanity/code input

### CODE REVIEW

**Comment by bjoerge** [comment]
> should we revisit the built in languages we bundle up? Not sure how much it adds to the size though.

Had the same thought, it would be a breaking change so didn't bother with it now, but we should probably consider deprecating all but maybe a very few defaults and plan to remove them in the long term.

These are the numbers for the language modes we currently include by default:
  Uncompressed: 1.24 MB
  Minified (uglify): 844 kB
  Minified and gzipped (level: default): 194 kB

**Review by rexxars — APPROVED** [review]
Nice!

**Comment by rexxars** [comment]
I agree that we should cut down the amount of languages we support out of the box, but this _is_ a breaking change, so I'd hold off on that for now. Maybe we should move the code input out of the monorepo and version it independently? That would allow us to make this breaking change.

**Comment by bjoerge** [comment]
> Maybe we should move the code input out of the monorepo and version it independently?

Yep, makes a lot of sense. Let's do it next time around? (nothing about this PR will complicate that as far as I can tell, so merged for now). Thanks for reviewing!

**Pull request merged**
