### PR TITLE
[form-builder] Support additional filter to reference input

### PR DESCRIPTION
**Pull request by rexxars**
Sometimes, you may want to be more specific about which documents to reference than just the document type. This is a basic implementation where you can pass a `filter` and an optional `filterParams` in the `options` object of reference fields.

Let the discussion commence!

### CODE REVIEW

**Comment by kmelve** [comment]
Cool! Should it be `params` like in the structure builder API?

**Comment by rexxars** [comment]
> Cool! Should it be `params` like in the structure builder API?

Not sure. There is a chance we will add other options to the reference fields at some point, which might make it hard to know what "params" applies to

**Comment by kmelve** [comment]
I'm not sure either. Does it make sense to use `params` here at all btw? Why wouldn't you just have it all in the `filter` expression?

E.g. we don't have `params` for `filter` in the access control (at least not documented).

**Comment by rexxars** [comment]
Not having params in filters seems like an oversight more than a feature. Parameters are more readable and less error-prone, so I definitely prefer it to string concatenation.

**Comment by rexxars** [comment]
After some discussion on Slack, I've changed the implementation to be able to take a function as `filter`, which can return `filter` and `params`. The function receives the document, the parent node and the parent path. With this, you should be able to create a constraint based on the surrounding document. I added an example in the test studios reference schema, where a nested object has a "decade" field and controls a sibling reference.

Also added validation of the properties. Will add help pages if PR is accepted.

**Comment by kmelve** [comment]
[this is super cool!]

**Comment by rexxars** [comment]
Help articles written. Will add documentation before release.

**Pull request merged**
