### PR TITLE
refactor(sanity): re-add sanity::versionOf

### PR DESCRIPTION
**Pull request by RitaDias**
### Description

Work in CL has finalised, so I'm re-adding the right query

❗ the query is not optimised for all datasets (including the one we are using by default in the studio), but this should not bea concern for this PR

### CODE REVIEW

**Comment by bjoerge** [comment]
LGTM - Do we want to hold off on merging until it's optimized for the test dataset?

**Comment by RitaDias** [comment]
> LGTM - Do we want to hold off on merging until it's optimized for the test dataset?

I don't recall specifics, but I think that Ash mentioned some changes that Radhe had done to some datasets on the studio. I _think_. I remember @juice49 mentioning something about this (though I'm not sure if it's connected to the versionOf optimisation specifically), can you confirm Ash?

Otherwise, I can also ask Radhe specifically to do what needs to be done for the test dataset (the [thread](https://sanity-io.slack.com/archives/C077WKSKVKK/p1724398615748769?thread_ts=1724398334.078339&cid=C077WKSKVKK) where I brought this up)?

**Comment by RitaDias** [comment]
> LGTM - Do we want to hold off on merging until it's optimized for the test dataset?

> I don't recall specifics, but I think that Ash mentioned some changes that Radhe had done to some datasets on the studio. I think. I remember @juice49 mentioning something about this (though I'm not sure if it's connected to the versionOf optimisation specifically), can you confirm Ash?

Otherwise, I can also ask Radhe specifically to do what needs to be done for the test dataset (the [thread](https://sanity-io.slack.com/archives/C077WKSKVKK/p1724398615748769?thread_ts=1724398334.078339&cid=C077WKSKVKK) where I brought this up)?

Just saw Ash's comment on slack and I think that maybe I will just use this branch as a base and push into it (which will be merged into corel whenever his larger changes go info effect)

**Review by pedrobonamin — APPROVED** [review]
Thanks Rita! Looks good to me

**Pull request merged**
