### PR TITLE
fix(structure): annotations not opening in portable text editor

### PR DESCRIPTION
**Pull request by pedrobonamin**
With the changes pushed in https://github.com/sanity-io/sanity/pull/6129 a bug was introduced into the PTE editor.
Annotations wont open.

The issue is generated by the onBlur action, when it's triggered, it's setting as `openPath` the blurred path. 
This specific change was introduced in that PR, possibly an oversight?

### Notes for release
Fixes an issue in PTE in which annotations were not opening by a bug introduced in v3.36.3

### CODE REVIEW

**Comment by rdunk** [comment]
Obviously lower priority than annotations, but just noting that this will reintroduce the scroll jumping issue with PTE in Presentation.

**Comment by skogsmaskin** [comment]
> Obviously lower priority than annotations, but just noting that this will reintroduce the scroll jumping issue with PTE in Presentation.

@rdunk - Could this scroll jumping perhaps be fixed by moving [these lines](https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/core/form/inputs/PortableText/hooks/useTrackFocusPath.tsx#L36-L50) down to line `59` ?

image

**Comment by rdunk** [comment]
@skogsmaskin I'll verify that as a workaround, I _think_ we tested that before but I'll double check.

Done some digging and looks like I didn't catch this as our test document didn't contain an Annotation, only InlineBlock.

[This line](https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx#L97), which is unique to Annotation's `onOpen` callback means that the blur is triggered _after_ the DocumentPane's `onPathOpen`/`setOpenPath` is called, for all the other PT objects, the blur is triggered before.

**Comment by rdunk** [comment]
Agreed with merging this as this bug is much worse than the scroll issue.

The problem is if an initial openPath is defined that references some block in the PTE, without setting the openPath on blur, the openPath is maintained as its initial value, which is incorrect. It's not the focus path we are setting to the blurred path, just the openPath, which AFAICT is correct.

I think ultimately the bug isn't caused by setting that openPath on blur, it is caused by the Annotation triggering the blur event _after_ it sets the openPath, which resets it.

**Review by rexxars — APPROVED** [review]

**Pull request merged**
