### PR TITLE
Collapsible button group in block editor

### PR DESCRIPTION
**Pull request by kristofferj**
- Auto-collapsing groups in toolbar when needed
- Insert menu supports not being collapsed
- Display a "show menu" button when there is no room for all
- Touch scrolling in mobile with paper-cut-shadow™ to show scrollability

### CODE REVIEW

**Comment by skogsmaskin** [comment]
Also get some warnings about missing React keys:

```
react-dom.development.js:506 Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in InsertMenu (created by PrimaryGroup)
    in div (created by PrimaryGroup)
    in div (created by PrimaryGroup)
    in PrimaryGroup (created by Component)
    in div (created by Component)
    in div (created by Component)
    in div (created by Component)
    in Component (created by Measure)
    in Measure (created by Toolbar)
    in Toolbar (created by BlockEditor)
```

**Comment by skogsmaskin** [comment]
Looks really promising! Please fix the above issues, and I'll look closer!

**Comment by kristofferj** [comment]
Cool!. Will test and debug in example studio

**Comment by kristofferj** [comment]
Did some fixes. Should also work in example-studio now.

**Comment by skogsmaskin** [comment]
@kristofferj - great work!

I'm approving if you remove the `flow-bin` update to package.json. Not sure which implications it will have.

**Comment by kristofferj** [comment]
@skogsmaskin done

**Comment by skogsmaskin** [comment]
Approved!

**Comment by kristofferj** [comment]
Cool. I wait until after the release to merge it, since I want it to be tested more before we merge.

**Pull request merged**
