### PR TITLE
[components] Fix theming issues

### PR DESCRIPTION
**Pull request by mariuslundgard**
**Type of change (check at least one)**

- [x]  Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  Documentation (fix or update to documentation)
- [ ]  Maintenance
- [ ]  Other, please describe:

**Does this change require a documentation update? (Check one)**

- [ ]  Yes
- [x]  No

**Current behavior**

- https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1597954763062400

**Description**

This fixes how inverted colors of `--brand-primary` and `--state-*-color` CSS variables are created, and also how the CSS variables are applied in the `DefaultButton`.

**Note for release**

**Checklist** 

- [x]  I have read the [Contributing Guidelines](https://github.com/sanity-io/sanity/blob/next/CONTRIBUTING.md)
- [x]  The PR title includes a link to the relevant issue
- [X]  The PR title is appropriately formatted: `[some-package] PR title (#123)`
- [x]  The code is linted
- [ ]  The test suite is passing
- [ ]  Corresponding changes to the documentation have been made

### CODE REVIEW

**Comment by vicbergquist** [comment]
> @vicbergquist The best way to test this is by running `npm run example-studio`. Try changing the theme override setting in `packages/example-studio/sanity.json` to:
> 
> ```
>     {
>       "implements": "part:@sanity/base/theme/variables/override-style",
>       "path": "./themes/yellow.css"
>     }
> ```

Thank you @mariuslundgard!
looks like there is still the issue with the tool text color always being this gray:
Screenshot 2020-08-24 at 10 27 33

Comes from `ToolSwitcherItem.css` L9 it seems:

 ```
@nest &:not(.selected) {
    @media (hover: hover) {
      color: var(--gray);

      @nest &:hover {
        color: inherit;
      }
    }
```

**Comment by mariuslundgard** [comment]
> looks like there is still the issue with the tool text color always being this gray

@vicbergquist Ah, I only looked at the `DefaultButton` issue. Can have a look at the nav bar too. Should I use the same PR?

**Comment by vicbergquist** [comment]
> > looks like there is still the issue with the tool text color always being this gray
> 
> @vicbergquist Ah, I only looked at the `DefaultButton` issue. Can have a look at the nav bar too. Should I use the same PR?

Yeah if the release doesn't need this, I guess you can use this PR? Dont think this is critical to the release and that they should be fixed together

**Comment by mariuslundgard** [comment]
@vicbergquist Can you test again now, and see if the Navbar looks as expected?

**Review by vicbergquist — APPROVED** [review]
Awesome, lgtm 🎉

**Pull request merged**
