### PR TITLE
feat(dashboard): add docs banner to sanity tutorials widget

### PR DESCRIPTION
**Pull request by vicbergquist**
### Description

This adds a banner at the top of the sanity tutorials videos with a CTA to our docs site.

### What to review

- Start the test studio and make sure everything works as it should in the dashboard with the banner/

### Notes for release

n/a

### CODE REVIEW

**Review by ninaandal — CHANGES_REQUESTED** [review]
Maybe fix this when the screen gets small? 

Screenshot 2022-07-28 at 11 54 22

**Comment by vicbergquist** [comment]
> Maybe fix this when the screen gets small?
> 
> Screenshot 2022-07-28 at 11 54 22

what size is this? I'm already adjusting the layout like this `<Flex direction={['column', 'column', 'row']}>` 🤔

**Comment by ninaandal** [comment]
Below `950px` ish, but it is with the right side banner open
Screenshot 2022-07-28 at 14 14 19

**Comment by vicbergquist** [comment]
> Below `950px` ish, but it is with the right side banner open
> Screenshot 2022-07-28 at 14 14 19

Hm does any important devices have that viewport width? If not, I'm not sure if it makes sense to fix it with container queries

**Review by ninaandal — APPROVED** [review]
Yeah, makes sense 👍 LGTM otherwise!

**Pull request merged**
