### PR TITLE
[desk-tool] Link to getting started guide if there are no schema types

### PR DESCRIPTION
**Pull request by bjoerge**
This displays a link to our getting started guide if there are no document types in schema. It's very basic, and should probably get some more work before merge.

### CODE REVIEW

**Comment by kristofferj** [comment]
LGTM

**Comment by kristofferj** [comment]
If we want to test this (and maybe style it), how de we trigger it?

**Comment by kristofferj** [comment]
"GettingStarted"-component should not be a pane imho. If there is no items, there is no need to show a SplitController.

**Comment by bjoerge** [comment]
> "GettingStarted"-component should not be a pane imho. If there is no items, there is no need to show a SplitController.

Agreed. Just couldn't figure out how to render it nicely otherwise.

**Pull request merged**
