### PR TITLE
chore(test): move to jest globals

### PR DESCRIPTION
**Pull request by bjoerge**
### Description
This moves away from jest relying on globals like `jest`, `test`, `it`, `describe`, etc. There's several benefits to this, but in general, having explicit imports is preferrable to implicit globals.

Other benefits:
- We were using `@types/jest` which is maintained separately from the jest source code. Jest ships its own types, which are probably more accurate. At least they are more strict and have less usage of `any`, which, as you can see in the follow up commits surfaced a handful of issues with our types.
- If we decide to move over to something else (e.g. vitest), having expclitic imports helps us, and likely will make it easier to have multiple test frameworks side by side

### What to review

Not yet ready to merge as there's one remaining issue with the e2e PTE collaboration tests that I haven't looked into yet

### Testing
These are modifications to the test suite only

### Notes for release

N/A internal only

### CODE REVIEW

**Comment by bjoerge** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5532?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `next`
  * **PR #5531** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5531?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #5534** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5534?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #5532** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5532?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
        * **PR #5533** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5533?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/sanity-io/sanity/5532?utm_source=stack-comment).

**Comment by rexxars** [comment]
What's the benefit/rationale?

**Comment by bjoerge** [comment]
> What's the benefit/rationale?

Outlined some in the PR description: https://github.com/sanity-io/sanity/pull/5532#issue-2092798110

**Review by sjelfull — APPROVED** [review]

**Review by juice49 — APPROVED** [review]
Very nice!

**Pull request merged**
