### PR TITLE
[form-builder] Feature: Hide fields by specifying `hidden` in schema

### PR DESCRIPTION
**Pull request by rexxars**
Warning: Totally new to the form builder internals, so might be overlooking something.

PR is an attempt to introduce new `isHidden` property on schema which will prevent a field from being rendered. The use case is where you have properties which are populated by scripts and are part of the content model, but should not be editable/shown to the editors in the studio.

### CODE REVIEW

**Comment by bjoerge** [comment]
Looks good! The only issue I have is that I've also added a `publicationYear` field to the book type in test-studio in the branch I'm currently working on, but first come, first served, so I'll rename mine 😅

**Comment by bjoerge** [comment]
Ah, and we already have the `readOnly`, which corresponds to the `<input readOnly` attribute. Maybe it should be `hidden` instead of `isHidden` ?

**Comment by rexxars** [comment]
Sure. I can change the example field name and change the name of the attribute as well.

**Comment by bjoerge** [comment]
Regarding the `is`-prefix: I'm not sure... we kind of decided on the general rule of prefixing boolean attributes, except in cases where there is a 1:1 correspondence with native dom element attributes. You could argue that since native dom inputs doesn't have a `hidden` attribute, it should be named `isHidden` here... but I think I'm in favor of `hidden`, since we already have `readOnly`.

**Comment by rexxars** [comment]
Changes made. Will squash when approved.

**Pull request merged**
