### PR TITLE
feat(structure): sheet list view patching

### PR DESCRIPTION
**Pull request by jordanl17**
### Description
Supporting patching single and multiple documents through sheet list view

### What to review
New hook `useDocumentSheetListOperations` added to subscribe to the visible documents and return their operations

### Testing
Testing for `DocumentSheetListPane` updated to also test that patchDocument is called as expected and the document operations are also executed

### Notes for release
No relevant notes as not customer facing

### CODE REVIEW

**Comment by juice49** [comment]
Hey! I'm seeing some failures when running the `packages/sanity/src/structure/panes/documentList/sheetList/__tests__/DocumentSheetListPane.test.tsx` test locally. It looks like [this is also happening in CI](https://github.com/sanity-io/sanity/actions/runs/9402330607/job/25896210511?pr=6866).

**Comment by jordanl17** [comment]
Lint is failing due to formatting in `edx-1351`, but to keep scope of PR smaller I haven't resolved those issues here

**Comment by jordanl17** [comment]
> Hey! I'm seeing some failures when running the `packages/sanity/src/structure/panes/documentList/sheetList/__tests__/DocumentSheetListPane.test.tsx` test locally. It looks like [this is also happening in CI](https://github.com/sanity-io/sanity/actions/runs/9402330607/job/25896210511?pr=6866).

Thanks - they've been resolve now

**Review by pedrobonamin — APPROVED** [review]
Looks good to me, thanks @jordanl17 !

**Pull request merged**
