### PR TITLE
refactor(studio-hints): migrate to `@sanity/ui`

### PR DESCRIPTION
**Pull request by hermanwikner**
### Description

Migrate studio-hints to `@sanity/ui`.

### What to review

Make sure that the studio-hints works as before. 

### Notes for release

Migrate studio-hints to `@sanity/ui`

### CODE REVIEW

**Review by vicbergquist — CHANGES_REQUESTED** [review]
Saw some tiny misalignment thing and active state that I messaged you about on Slack, but other than that it looks great 👍

**Review by rexxars — COMMENTED** [review]
In the old version, the hints "button" seemed to be "active" when the sidebar was open:
image

In the new one, it does _not_ seem to be:
image

Is this intentional?

The heading font color also seems to have more contrast in the old one - not sure if this is just the intended style of the new UI library or not?

**Comment by hermanwikner** [comment]
Thanks! I fixed the things you commented on. 👍

**Review by rexxars — APPROVED** [review]
Looks good!

**Pull request merged**
