### PR TITLE
chore(sanity): :zap: add sideEffects: false to package.json for smaller bundles

### LINKED ISSUE #4711: Add "sideEffects": false to sanity package.json
**Is your feature request related to a problem? Please describe.**
We have some shared code in our monorepo, some of which uses some code from the main sanity module. However, sanity doesn't have "sideEffects": false, so it ends up adding almost 2mb to our final bundle! I know this because, after going into node_modules/sanity/package.json and adding that field, it seems to have really trimmed the fat on what is there.
The studio preview seems to run like normal, and our app builds great, but I'm unsure of any real unintended "side-effects" that may exist on your side.
Is there a reason not to add this field to your package.json to make the sanity lib more tree-shakeable?

**Describe the solution you'd like**
add `"sideEffects": false` to the main sanity `package.json`

**Describe alternatives you've considered**
Monkey patching it myself so my bundle will be smaller 🙃 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mckelveygreg**
### Description

Adding `"sideEffects": false` helps bundlers shake out more dead code resulting in smaller bundles of anything library consuming the base `sanity` package. 

Fixes #4711 

### What to review

Confirm no dependent packages were depending on `sideEffect` code.

### Notes for release

Add sideEffects: false to package.json for smaller bundles

### CODE REVIEW

**Review by stipsan — APPROVED** [review]
Good catch! I was under the impression we already used `sideEffects: false` in this package. 
I recommend we do a canary release of this before merging, so I can test if everything works when embedding the Studio in frameworks like Next.js and similar 🙌

**Comment by bjoerge** [comment]
@stipsan - I just released a canary from this branch if you'd like to take it for a spin: `3.15.2-canary.1+9f90482027`

**Comment by stipsan** [comment]
> @stipsan - I just released a canary from this branch if you'd like to take it for a spin: `3.15.2-canary.1+9f90482027`

Thanks, I will!

**Comment by stipsan** [comment]
Ran a test, good news is nothing broke. Maybe bad news, the size reduction were minimal. That said, the SWC minifying in NextJS is already very optimised and doesn't necessarily mean there won't be more to gain in other bundlers.

<details>
<summary>Before</summary>

Screenshot 2023-08-15 at 14 50 19


</details>

<details>
<summary>After</summary>

Screenshot 2023-08-15 at 14 48 21



</details>

**Review by bjoerge — APPROVED** [review]
Thanks for testing, @stipsan

**Comment by mckelveygreg** [comment]
Whelp, here's for hoping! Thanks all!!

**Pull request merged**
