### PR TITLE
refactor(field): migrate portableText diffs to @sanity/ui

### PR DESCRIPTION
**Pull request by vicbergquist**
**Note:** builds on #2592, so this branch should be rebased and reviewed afterwards.

### Description

This migrates the portable text diff type components to @sanity/ui and styled-compoenents.

Here is a before (left) and after (right).

Screenshot 2021-07-01 at 17 00 01

### What to review

- Test the review changes panel where changes are made in pt blocks.

### Notes for release

- Migrated PT diff components to @sanity/ui and styled-components

### CODE REVIEW

**Comment by rexxars** [comment]
This isn't a _regression_ since it has the same behavior in `next`, but maybe you could have a look and see if you can figure out why this is happening?
image

URL: https://test-studio.sanity.build/test/desk/blocksTest;a5533b89-dc3d-44e7-8ad4-611ef893d728%2Csince%3D%40lastPublished

Feel free to pull in @skogsmaskin if you need help

**Comment by skogsmaskin** [comment]
Not sure if this is trivial to fix (nested popovers), and should probably be followed up in its own task.

**Review by skogsmaskin — APPROVED** [review]
Looks good! :+1:

**Comment by vicbergquist** [comment]
> This isn't a _regression_ since it has the same behavior in `next`, but maybe you could have a look and see if you can figure out why this is happening?
> 
> image
> 
> 
> 
> URL: https://test-studio.sanity.build/test/desk/blocksTest;a5533b89-dc3d-44e7-8ad4-611ef893d728%2Csince%3D%40lastPublished
> 
> 
> 
> Feel free to pull in @skogsmaskin if you need help

Yeah I tried to fix it with a couple of different approaches, but wasn't able to. Can ask pk about it when I have time 👍

**Pull request merged**
