### PR TITLE
refactor(base): move icons to __legacy directory

### PR DESCRIPTION
**Pull request by mariuslundgard**
### Description

- The icons in `@sanity/base` have been moved to `packages/@sanity/base/src/__legacy/components/icons` as they are superseded by `@sanity/icons` now.
- The `sanity.json` file has been updated so e.g. `part:@sanity/base/file-icon` points to `__legacy/components/icons/File` instead of `components/icons/File`.

### What to review

- That the part-imports of icons still work as expected.

### Notes for release

- n/a

### CODE REVIEW

**Review by bjoerge — APPROVED** [review]
LGTM!

**Comment by rexxars** [comment]
I'm worried that people have imported from `lib/components/icons` - I seem to already recall seeing this in some third party code. Should we add deprecation proxies, or leave them as-is?

**Review by rexxars — CHANGES_REQUESTED** [review]
It would be nice to have a page listing all the available icons in @sanity/icons so you know how to migrate, and then add deprecation proxies telling the user to migrate and return the icon from the new location.

**Comment by mariuslundgard** [comment]
@rexxars If we need to leave deprecation proxies, then this change is not needed. The whole point is to make it easier to see what is legacy / soon to be deprecated, and what is being actively maintained. Let’s just close this PR?

**Comment by rexxars** [comment]
Agreed!

**Pull request closed without merging**
