### PR TITLE
[base, desk-tool] Update useTimeAgo hook to make trailing `ago` optional, and update sparkline to use minimal timestamp

### PR DESCRIPTION
**Pull request by vicbergquist**
**Type of change (check at least one)**

- [x]  Bug fix (non-breaking change which fixes an issue)

**Description**

Noticed that the sparkline doesn't currently use the minimal timestamp format, which sometimes makes it hard to read + causing layout issues when document was only published or updated a while ago. Also didn't match the Figma sketch.

This uses the minimal format for the timestamp in the sparkline, but also adds an option called `useAgo` to the `useTimeAgo` hook to make it possible to use both the default and minimal format with and without a trailing `ago`. 

The components using the `useTimeAgo` hook with the minimal format have been updated to use the appropriate `ago` as well.

**Note for release**

**Checklist** 

- [x]  I have read the [Contributing Guidelines](https://github.com/sanity-io/sanity/blob/next/CONTRIBUTING.md)
- [x]  The PR title is appropriately formatted: `[some-package] PR title (#123)`
- [x]  The code is linted

### CODE REVIEW

**Comment by mariuslundgard** [comment]
Looks good! The only issue I have is with the option name. By having `use` in the name, it can be confused with a React hook name. How about renaming to e.g. `agoSuffix`?

**Comment by vicbergquist** [comment]
> Looks good! The only issue I have is with the option name. By having `use` in the name, it can be confused with a React hook name. How about renaming to e.g. `agoSuffix`?

that's true! `agoSuffix` is good!

**Comment by vicbergquist** [comment]
Updated 👍

**Review by mariuslundgard — APPROVED** [review]
LGTM

**Pull request merged**
