### PR TITLE
[base] Expose client as CommonJS

### PR DESCRIPTION
**Pull request by rexxars**

### CODE REVIEW

**Comment by bjoerge** [comment]
Hm... this would be a breaking change, right? Thinking of consumers that previously did `const client = require('@santiy/client').default`?

**Comment by rexxars** [comment]
Yup. Not quite sure how many are using this right now as it needs the part system to operate.

**Comment by bjoerge** [comment]
Ok, just to be safe we could add a getter on `exports.default`, issue a warning and return the client?

**Comment by rexxars** [comment]
Good call. I've added a getter that `console.warn`s a deprecation message and added some basic tests.
The interop require code that babel insert looks like this:

```js
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj }
}
```

Since `__esModule` is not present when using `module.exports`, the `default` property should never be accessed if you're using Babel.

**Comment by bjoerge** [comment]
LGTM 🎊

**Pull request merged**
