### PR TITLE
[core] Honor --dataset option on get/query/create/delete CLI commands

### PR DESCRIPTION
**Pull request by thomax**

### CODE REVIEW

**Comment by bjoerge** [comment]
Looks like it could need a rebase against current `next`

**Comment by rexxars** [comment]
Perhaps also squash the three relevant commits?

**Comment by thomax** [comment]
@rexxars and @bjoerge Sound suggestions!

**Comment by rexxars** [comment]
I see that most of these commands are missing a help text. If you have time, it would be great if you could add that as well. The create command has an example, and should have the `--dataset` flag added.

**Comment by rexxars** [comment]
The dataset option is still missing in most commands help text

**Pull request merged**
