### PR TITLE
chore: move development repos to `dev/`

### PR DESCRIPTION
**Pull request by mariuslundgard**
### Description

This PR moves the following apps from `examples/` to `dev/`:
- `depcheck-test`
- `design-studio`
- `example-studio`
- `perf-studio`
- `storybook`
- `test-studio`

### What to review

- That these scripts work as they should:
  - `npm start`
  - `npm run dev`
  - `npm run workshop`
  - `npm run deploy-test`
  - `npm run ecommerce-studio`
  - `npm run test-studio`
  - `npm run clean-studio`
  - `npm run design-studio`
  - `npm run perf-studio`
  - `npm run example-studio`
  - `npm run movies-studio`
  - `npm run blog-studio`
  - `npm run test-e2e`
  - `npm run test-perf`

### CODE REVIEW

**Review by bjoerge — CHANGES_REQUESTED** [review]
- There are some merge conflicts that needs to be sorted out
- The commit `build(generate-help-url): remove unused dependency` should be removed since the dependency is in actually in use (see .eslintrc).
- There are some eslint errors that would be good to fix before merge (if not too much work)
- After merge I believe we need to update the Vercel deployment config to look for built files in the right directory

Otherwise LGTM!

**Comment by rexxars** [comment]
@mariuslundgard This one needs to be rebased, but I'm +1 for moving these out of "examples" as that's not really what they are.

**Comment by rexxars** [comment]
Vercel deployments seems to be failing, but I assume that is deployment configuration that needs to be updated post-merge? Wonder if this could be moved into the repo or not.

**Comment by mariuslundgard** [comment]
@rexxars 
> Vercel deployments seems to be failing, but I assume that is deployment configuration that needs to be updated post-merge? Wonder if this could be moved into the repo or not.

It can't be encoded in the PR, but could be done the moment before merging, so it builds after merge.

**Review by rexxars — APPROVED** [review]

**Pull request merged**
