### PR TITLE
fix: dark-mode checkerboard for images

### PR DESCRIPTION
**Pull request by snorrees**
### Description

Use checkerboard from sanity/ui.

image

### What to review

Ok to keep the Checkerboard file around?

### Notes for release

Checkerboard background for images now has a dark mode.

### CODE REVIEW

**Comment by mariuslundgard** [comment]
We should refactor the thumbs to use `<Card __unstable_checkered>` from Sanity UI: see [arcade example here](https://www.sanity.io/ui/arcade?mode=jsx&jsx=eJxdjs0OwiAQhO99ig1nkvp%2FMIWLiS9hTEPLtqAEDdBobfruFqwevO3M7Oy3xUE4CQp1qwIjjTaGwF1IqW3LhtOawobClsLuPILXr%2BiS6uYkOsIzgOJo8AnC6NYyUqMNk%2F937NL5oJv%2BF8faVIzYNAGUZWd9EJXBslZYX9HhN%2FqgZuFDb5ANw0PLoPawXC3ozEpiHNNenv7K42M8K%2FLI4dkbo0JFdg%3D%3D&title=Checkered+Card).

**Comment by snorrees** [comment]
> We should refactor the thumbs to use `<Card __unstable_checkered>` from Sanity UI: see [arcade example here](https://www.sanity.io/ui/arcade?mode=jsx&jsx=eJxdjs0OwiAQhO99ig1nkvp%2FMIWLiS9hTEPLtqAEDdBobfruFqwevO3M7Oy3xUE4CQp1qwIjjTaGwF1IqW3LhtOawobClsLuPILXr%2BiS6uYkOsIzgOJo8AnC6NYyUqMNk%2F937NL5oJv%2BF8faVIzYNAGUZWd9EJXBslZYX9HhN%2FqgZuFDb5ANw0PLoPawXC3ozEpiHNNenv7K42M8K%2FLI4dkbo0JFdg%3D%3D&title=Checkered+Card).

Done!

**Review by hermanwikner — COMMENTED** [review]
Nice!

Thought: Is it really necessary to have the `Checkerboard` component 🤔 I guess we could also just use the `Card` with the `__unstable_checkered` prop directly in `ImageToolInput` as well!

**Comment by mariuslundgard** [comment]
Agreed @hermanwikner 👍

**Review by mariuslundgard — APPROVED** [review]
✨

**Review by mariuslundgard — APPROVED** [review]

**Pull request merged**
