### PR TITLE
[language-filter] add defaultLanguage option

### PR DESCRIPTION
**Pull request by spacedawwwg**
**Type of change (check at least one)**

- [x]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x]  Documentation (fix or update to documentation)
- [ ]  Maintenance
- [ ]  Other, please describe:

**Does this change require a documentation update? (Check one)**

- [x]  Yes
- [ ]  No

**Current behavior**

Language filter hides/shows field level translation fields

**Description**

Added the option of a defaultLanguage that can't be be disabled/toggled. Also added minimal fixes to make toggle button keyboard accessible.

**Note for release**

Language filter has the added option of a `defaultLanguage` that can't be be disabled/toggled. Also added minimal fixes to make toggle button keyboard accessible.

**Checklist** 

- [x]  I have read the [Contributing Guidelines](https://github.com/sanity-io/sanity/blob/next/CONTRIBUTING.md)
- [x]  The PR title includes a link to the relevant issue
- [x]  The PR title is appropriately formatted: `[some-package] PR title (#123)`
- [x]  The code is linted
- [x]  The test suite is passing
- [x]  Corresponding changes to the documentation have been made

### CODE REVIEW

**Comment by bjoerge** [comment]
This looks very nice @spacedawwwg, thank you for this!

I did a few modifications to your PR here: https://github.com/sanity-io/sanity/commit/ac941e59d

In short:
- it will make sure we apply the defaults at the datastore level so we don't need to wait for user action to apply them
- changed the option to be an array of language ids instead of a single id in order to support having more than one default
- if `defaultLanguages` is configured, these languages will be the only fields shown initially before user selects anything from the menu.

Let me know if this works for you.

**Comment by spacedawwwg** [comment]
> This looks very nice @spacedawwwg, thank you for this!
> 
> I did a few modifications to your PR here: [ac941e5](https://github.com/sanity-io/sanity/commit/ac941e59d)
> 
> In short:
> 
> * it will make sure we apply the defaults at the datastore level so we don't need to wait for user action to apply them
> * changed the option to be an array of language ids instead of a single id in order to support having more than one default
> * if `defaultLanguages` is configured, these languages will be the only fields shown initially before user selects anything from the menu.
> 
> Let me know if this works for you.

This is great, @bjoerge - on board with all of that

**Comment by runeb** [comment]
@bjoerge Just to be clear, did we change the API in Sanity so this PR needs to be updated?

**Comment by bjoerge** [comment]
@runeb No updates needed for this PR, will merge the `feature/language-filter-default-option` branch which includes the changes from this PR with my modifications asap.

**Comment by bjoerge** [comment]
Merged in 55c6332

**Pull request closed without merging**
