### PR TITLE
[diff-patch] Add new diff-patch module

### PR DESCRIPTION
**Pull request by rexxars**
This introduces a new module (`@sanity/diff-patch`) which takes two objects (such as two documents) and generates an object of patch operations describing the differences between the two items.

There are a few optimizations that could be done if given some more time (and possibly a few changes/additions to the patch API), but I think this is a good start.

### CODE REVIEW

**Comment by bjoerge** [comment]
This is suuuuper exciting 😍! Did you have a specific use case in mind for this? I can see several, just curious to hear your thoughts.

A use case I'm thinking about is to use it for creating visual diffs in the UI (e.g. to preview changes before publishing), among others.

**Comment by rexxars** [comment]
Yes, [this branch](https://github.com/sanity-io/sanity/tree/diff-publish) is scheduled and significantly improves the desk tool publishing process by only applying the diff between the published and the draft. For this to work I needed this module, but there's plenty of other use cases, as you said.

**Comment by bjoerge** [comment]
Awesome!

**Comment by simen** [comment]
It is hard to ascertain the correctness of the algorithm from reading it alone, but it looks credible. Should we have more test-cases here? Should be possible to generate a lot of test cases algorithmically?

Since the resulting patch uses indexing, not keys, to target mutations we should possibly automatically add an `ifRevisionId`-constraint (based on the source document) to the first patch in order to document that this is dangerous to apply without such a clause? Alternatively we should possibly always use keys when possible?

There are a number of things we could do to improve "patchability" without requiring revision id protection. When selecting multiple object array elements we could:

`array[key == "a", key == "b", key == "c"]` selects all three elements.

For primitives:

`array[7][@ == "bananas"]` selects array element 7 only if its value still is "bananas".

But this is probably a lot of work with limited value. I'd go for adding the ifRevision-constraint.

**Comment by rexxars** [comment]
OK, did some more work on this:

- Added integration tests that perform the actual mutations against the API and ensures that the expected result is the one returned by the server.
- Added an option to include a revision lock (`ifRevisionId`)
- Patch operations are split into individual mutations per type instead of one big patch. This also allowed using the insert patch

Still feel like we/I should try to improve the array handling - simple cases like removing an array element causes a massive reflow of set operations instead of simply removing the element in question.

**Comment by skogsmaskin** [comment]
Any progress on this one? Maybe try to rebase it against `next` if it's still on?

**Comment by rexxars** [comment]
Decided to move this into a separate repo and maintain it on a volunteer basis instead, so as not to bring more maintenance burden upon the team: https://github.com/rexxars/sanity-diff-patch

**Pull request closed without merging**
