### PR TITLE
fix(desk): use custom sort order by default and only use defaultOrdering as fallback

### PR DESCRIPTION
**Pull request by vicmeow**
### Description

Custom sorts were broken and document list would not update with the correct sort order when changing sort order from the pane menu. 

### What to review

Make sure that ordering works as expected

### Notes for release

- Fixed an issue where custom sort orders were broken

### CODE REVIEW

**Comment by bjoerge** [comment]
Will this reincarnate #2947?

**Comment by vicbergquist** [comment]
> Will this reincarnate #2947?

aah.. probably. Will look for a fix to make sure it doesn't happen

**Comment by vicbergquist** [comment]
> > Will this reincarnate #2947?
> 
> aah.. probably. Will look for a fix to make sure it doesn't happen

I believe I found a fix. You can test it by adding `.defaultOrdering([{field: 'title', direction: 'asc'}])` on the document list for `Custom books list` in `resolveStructure.ts`, and then using the sort menu in the pane header.

**Comment by skogsmaskin** [comment]
Rebased and set the correct branch for this.

**Review by skogsmaskin — APPROVED** [review]

**Comment by rexxars** [comment]
@vicmeow I did a few minor changes, see the last three individual commits and tell me if they look good to you:

1. The default ordering option is no longer used in `useDocumentList`, so I removed the option to avoid confusion
2. The memoization did not account for an update in the desk structure `defaultOrdering` - it _shouldn't_ cause a lot of re-renderings to include it in the dependency array and should ensure we update the sort order on desk structure change
3. For some reason the default sort order code-wise was set to creation date, but as far as I can remember we've always defaulted to last _updated_ - agree?

**Review by rexxars — APPROVED** [review]

**Comment by geball** [comment]
I tried testing this branch against test-studio and got some orderings I couldn't explain. For example, Author documents (`/test/content/author`) sorted by Name have a single document out of place at the top, and then appear to sort correctly.
Author documents sorted by 'asdddfxx !' then numbers, and finally by letters.

Book documents (`/test/content/book`) have a custom ordering in the schema, and Sort by Swedish title doesn't seem to be followed.

**Comment by rexxars** [comment]
> For example, Author documents (`/test/content/author`) sorted by Name have a single document out of place at the top, and then appear to sort correctly. 

It is confusing - this is caused by the drafts vs published document: the published document starts with the characters `!!`, while the draft removes these. So it looks like it is wrong because what you're seeing the title of is the draft. This is of course less than ideal, but it is hard to work around since the backend returns all documents regardless of status, and we then have to collate them on the client side - leading to this situation. We could potentially client-side order them once they are collated, but this would lead to inconsistent behavior when scrolling (we're lazy-loading results).

> Book documents (`/test/content/book`) have a custom ordering in the schema, and Sort by Swedish title doesn't seem to be followed.

This has the same issue. There are other "user experience" ordering issues too; if a field starts with a space (or is just whitespace in general), it is sorted to the top of the list, since those characters sort prior to letters. This is usually not what you want (it can be hard to tell that they have leading whitespace).

I still feel like this PR improves on the _current_ situation, and then we can work on getting an improved ordering figured out, although it might require some creative queries or API changes.

**Comment by geball** [comment]
I appreciate that explanation! Thanks @rexxars.

**Review by geball — APPROVED** [review]
Looks good, @vicmeow!

**Pull request merged**
