### PR TITLE
fix(form): read only issues

### PR DESCRIPTION
**Pull request by hermanwikner**
### Description
This PR fixes read only issues. 

### What to review

Make sure that read only works as expected.

### Notes for release
fix(form): read only issues

### CODE REVIEW

**Review by bjoerge — APPROVED** [review]
Great work, @hermanwikner! 👏🏼

**Review by rexxars — CHANGES_REQUESTED** [review]
I seem to still be able to edit nested content - take a look at the `Polymorphic grid array` [in the test studio](https://test-studio-62uxmafmy.sanity.build/test/content/input-debug;readOnlyTest;9c0979b7-a202-44a3-a645-88a93499b47c) - you cannot add _new_ items, but you can still edit _existing_ items.

**Comment by hermanwikner** [comment]
> I seem to still be able to edit nested content - take a look at the `Polymorphic grid array` [in the test studio](https://test-studio-62uxmafmy.sanity.build/test/content/input-debug;readOnlyTest;9c0979b7-a202-44a3-a645-88a93499b47c) - you cannot add _new_ items, but you can still edit _existing_ items.

Added a fix – can you try again @rexxars?

**Comment by rexxars** [comment]
> Added a fix – can you try again @rexxars?

👨‍🍳 Works now!

**Review by rexxars — APPROVED** [review]

**Pull request merged**
