### PR TITLE
feat(cli): merge user vite config object

### PR DESCRIPTION
**Pull request by nkgentile**
### Description

- (Fix?) Respect user configuration when running `sanity preview`
- Allow user to pass configuration object that will be merged into default Vite configuration
- Align user configuration function with Vite's API by [passing context as second argument](https://vitejs.dev/config/#conditional-config) and accept a Promise:
```ts
import {defineCliConfig} from 'sanity/cli'
import {mergeConfig} from 'vite'

export default defineCliConfig({
  // ...rest of config

  async vite(config, {command, mode}){
    const target = await getProxyTarget()

    return mergeConfig(config, {
      server: {
        proxy: {
          "/api": {
            target,
            changeOrigin: true,
            secure: false,
            rewrite: (path) => path.replace(/^\/api/, ""),
          },
        },
      },
    })
  }
})
```

### What to review

1. Bootstrap a new Sanity Studio v3 project, with TypeScript
2. In `sanity.config.ts` add a `vite` property to check Intellisense and add:
```ts
import {defineCliConfig} from 'sanity/cli'

export default defineCliConfig({
  // ...rest of config

  vite: {
    server: {
      open: true
    }
  }
})
```

### CODE REVIEW

**Comment by nkgentile** [comment]
In the example above:
```ts
import {defineCliConfig} from 'sanity/cli'
import {mergeConfig} from 'vite'

export default defineCliConfig({
  // ...rest of config

  async vite(config, {command, mode}){
    const target = await getProxyTarget()

    return mergeConfig(config, {
      server: {
        proxy: {
          "/api": {
            target,
            changeOrigin: true,
            secure: false,
            rewrite: (path) => path.replace(/^\/api/, ""),
          },
        },
      },
    })
  }
})
```
I had to add `vite` as a `devDependency` to use `mergeConfig`, but I wonder if the function signature could provide it in the arguments somewhere? 🤔

**Comment by rexxars** [comment]
I really want to land this, but it would mean having to ship vite as a non-dev dependency in `@sanity/cli` in order for the types to ship. Would love to find a solution to this, but don't currently have the bandwidth. Any thoughts?

**Comment by nkgentile** [comment]
Is it a no-no to add the missing exports in `vite.d.ts` and then rely on declaration merging? Worst case, a user only has `@sanity/cli` installed and they don't get autocomplete in `defineCliConfig`?

**Comment by rexxars** [comment]
> Is it a no-no to add the missing exports in `vite.d.ts` and then rely on declaration merging? Worst case, a user only has `@sanity/cli` installed and they don't get autocomplete in `defineCliConfig`?

Hmm, no, that seems like a decent enough option.

**Review by rexxars — APPROVED** [review]

**Pull request merged**
