### PR TITLE
Rewrite date inputs to use date picker based on UI

### PR DESCRIPTION
**Pull request by bjoerge**
**Type of change (check at least one)**

- [x]  Maintenance

**Does this change require a documentation update? (Check one)**

- [x]  No

**Description**
This is a complete rewrite of our default date+datetime input to a new one that's based on Sanity UI.

**Note for release**

Migrates default date and datetime inputs to use Sanity UI

### CODE REVIEW

**Review by rexxars — APPROVED** [review]
Looks great! Found a few edge-cases, though:

**Comment by rexxars** [comment]
Found a couple of edge-cases:

On short browser windows, the date picker sometimes pushes the footer... up? Kind of weird
image

**Comment by rexxars** [comment]
On mobile there's also some odd similar behavior:
image

**Review by rexxars — CHANGES_REQUESTED** [review]
I think the mobile bug needs to be looked at, at least.

**Comment by bjoerge** [comment]
> I think the mobile bug needs to be looked at, at least.

Added a workaround for this in 770e16c.

**Pull request merged**
