### PR TITLE
fix(core): focus handling and dialog behavior

### PR DESCRIPTION
**Pull request by hermanwikner**
### Description
This pull request implements:
- Consistent dialog behavior. In order to be able to do this, `@sanity/ui` has been updated to `1.2.0` where improvements to the `Dialog` component were introduced. 
- Some focus issues in the image and file input.

### What to review
- When several dialogs are open at the same time with split panes, you should only be able to close one of the dialogs (with "Escape" or click outside)
- Image and file input is usable with keyboard

### Notes for release
n/a

### CODE REVIEW

**Review by mikolajdobrucki — APPROVED** [review]
LGTM! 🚀

**Comment by skogsmaskin** [comment]
I'm testing the following, but I'm not sure if it's part of what we are trying to solve here, but:

1) I open a image crop tool modal
2) I open up "Inspect document" modal.
3) Both modals are shown
4) I press ESC
5) Both modals are closed.

I would at least argue that ESC should not close both of them?

Should the image modal close when I open the "inspect" modal?

**Review by mikolajdobrucki — APPROVED** [review]

**Comment by mikolajdobrucki** [comment]
> I'm testing the following, but I'm not sure if it's part of what we are trying to solve here, but:
> 
> 1. I open a image crop tool modal
> 2. I open up "Inspect document" modal.
> 3. Both modals are shown
> 4. I press ESC
> 5. Both modals are closed.
> 
> I would at least argue that ESC should not close both of them?
> 
> Should the image modal close when I open the "inspect" modal?

I would agree that  ESC should not close both dialogs at the same time. 
It is not a regression though (afaik it was always like this) so I would treat that as a separate issue not blocking for release
therefore accepted the PR 👍

**Comment by bjoerge** [comment]
Took the liberty of rebasing against next

**Review by bjoerge — APPROVED** [review]
Did a round of testing and works great from what I can tell! ✨

**Pull request merged**
