### PR TITLE
[components] Replace LayerStack with utility components

### PR DESCRIPTION
**Pull request by bjoerge**
Replaces LayerStack with a StackedEscapable component that keeps track of a stack of "escapable" components (strictly they doesn't have to be layered). Also adds a bit of cleanup here and there.

### CODE REVIEW

**Comment by kristofferj** [comment]
Good work. But this will probably close all components when clicking outside? The layerstack did also prevent other layers from closing when clicking outside.

**Comment by bjoerge** [comment]
> But this will probably close all components when clicking outside?
Not sure? Can you point me to where it is not working? In any case, responding to click outside is a different concern and should be handled differently IMO.

**Comment by kristofferj** [comment]
The handleWindowClick method in Sticky.js will always just return now. It is based on that the state we used to set with layerstack.

**Comment by bjoerge** [comment]
Also added a `<CaptureOutsideClicks` utility component that should address the outside click issue.

**Comment by bjoerge** [comment]
Hand-merged in 22923c13d

**Pull request closed without merging**
