### PR TITLE
[cli] add command for changing externalStudioHost in manage

### PR DESCRIPTION
**Pull request by vicbergquist**
**Type of change (check at least one)**

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  Documentation (fix or update to documentation)
- [ ]  Maintenance
- [ ]  Other, please describe:

**Does this change require a documentation update? (Check one)**

- [x]  Yes
- [ ]  No

**Current behavior**

We currently only provide a tacky solution for changing the Studio URL shown in the project management UI.

**Description**

This adds a new command to the CLI that adds or changes the value of `externalStudioHost` that then changes the Studio URL in manage.

To do:
- [ ] discuss command name 
- [x] add --unset flag to unset the `externalStudioHost` value.

**Note for release**

[coming soon]

**Checklist** 

- [x]  I have read the [Contributing Guidelines](https://github.com/sanity-io/sanity/blob/next/CONTRIBUTING.md)
- [x]  The PR title includes a link to the relevant issue
- [x]  The PR title is appropriately formatted: `[some-package] PR title (#123)`
- [x]  The code is linted
- [x]  The test suite is passing
- [ ]  Corresponding changes to the documentation have been made

### CODE REVIEW

**Comment by vicbergquist** [comment]
Yes! I think renaming the command would make it clearer as well. There key are two keys that can be mixed up I think:`studioHost` and `externalStudioHost`. The latter is on the metadata object, and is the one that this command will change.

**Comment by vicbergquist** [comment]
I did some refactoring and changed some naming for clarity. Also added an `--unset` flag 😊

**Comment by thomax** [comment]
Great job @vicbergquist!

In Populus, this field is called `externalStudioHost` (not `externalStudioUrl`). It would probably make sense to keep those in line?

**Comment by vicbergquist** [comment]
> Great job @vicbergquist!
> 
> Would it make sense to keep CLI command in line with the internal Populus field name (`externalStudioHost`)?
> 
> In such a way that you write `sanity projects externalStudioHost <studio-host>` instead of `sanity projects externalStudioUrl <studio-url>`?

I thought so too, but also, with `externalStudioUrl` it's clearer that you're only changing just the URL 🤔

**Comment by vicbergquist** [comment]
Closing because of possible alternative solution.

**Pull request closed without merging**
