### PR TITLE
[ecommerce-studio] Change blurb to from localText to localeString

### PR DESCRIPTION
**Pull request by evenwestvang**
Trivial change form text to strings for blurbs.

### CODE REVIEW

**Comment by bjoerge** [comment]
Will this require the dataset to be updated and reexported too?

**Comment by kristofferj** [comment]
Is text and string compatible?

**Comment by bjoerge** [comment]
Yeah, they are interchangeable, so this should work fine.

**Comment by kristofferj** [comment]
@evenwestvang If you want your changes included in next, you need to merge this

**Pull request merged**
