### PR TITLE
fix(schema): validate that object has no standalone block fields

### LINKED ISSUE #4152: Sanity v2 to v3 breaks `block` fields
It was previously possible to assign `block` fields directly to objects in v2. In v3, this causes full page crashes when content editors ‘Convert the value’.

### PR DESCRIPTION
**Pull request by pauloborges**
### Description

This PR fixes addresses the issue #4152, in which Sanity Studio accepts standalone `block` fields, but crashes when trying to render the "edit form". The PR enhances the `object` validation to also check for these fields, and adds a problem when at least one such field is found.

This PR also introduces a new "help id" `STANDALONE_BLOCK_TYPE`. A new help page with the slug `schema-standalone-block-type` needs to be created. 

### What to review

* No schema validation issue when an `object`/`document` has no standalone `block` fields.
* Schema validation issues a problem when an `object`/`document` has 1 or more standalone `block` fields.

I tested it with the following `document`:

```
{
  title: 'Document with blocks',
  name: 'docBlocks',
  type: 'document',
  fields: [
    {
      title: 'Title',
      name: 'title',
      type: 'string',
    },
    {
      title: 'Blocks',
      name: 'blocks',
      type: 'array',
      of: [{type: 'block'}],
    },
    // {
    //   name: 'field1',
    //   title: 'Block 1',
    //   type: 'block',
    // },
    // {
    //   name: 'field2',
    //   title: 'Block 2',
    //   type: 'block',
    // },
  ],
}
```

When `field1` is present:

Screenshot 2023-02-22 at 21 17 00

When both `field1` and `field2` are present:

Screenshot 2023-02-22 at 21 16 28

### Notes for release

Something along the lines of:

> Introduces a missing `object` validation to prevent standalone `block` fields to exist.

### CODE REVIEW

**Review by rexxars — APPROVED** [review]
This is great, thank you Paulo! 
Ideally we would add a test for this. I'll also see if I can find time to create the help page for this error.

**Comment by pauloborges** [comment]
Thanks, Espen! I can definitely add a test for this one sometime this week!

**Comment by rexxars** [comment]
> Thanks, Espen! I can definitely add a test for this one sometime this week!

Oh excellent, that would be much appreciated! Thanks again 🙏

**Comment by pauloborges** [comment]
Hello again!

I've added a test covering both happy and sad paths. But to be honest, I was a bit unsure _where_ to put the test, and which API to test. Hopefully this is good enough! Let me know if you think this can be improved somehow.

**Comment by rexxars** [comment]
Did some minor refactoring and merged as https://github.com/sanity-io/sanity/commit/e6b7ae9fa19480029fea83c09d2bc531b89309cb - thank you Paulo!

**Pull request closed without merging**
