### PR TITLE
fix(cli): graphql api flag is respected during validation

### PR DESCRIPTION
**Pull request by mwain**
### Description
During GraphQL deployment we validate APIs have unique dataset/tag. This check wasn't respecting the `--api` CLI flag.

Ref CLDX-2142

### What to review

* Test the graphql deploy command
* Is this behaviour expected?

### Testing

Tested locally with various GQL API configs, and command line args

### CODE REVIEW

**Review by binoy14 — COMMENTED** [review]
Changes makes sense to me. Although is it possible to add some tests for this? looks like there are already some tests [here](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/cli/test/graphql.test.ts) for graphql cli.

**Comment by mwain** [comment]
> Changes makes sense to me. Although is it possible to add some tests for this? looks like there are already some tests [here](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/cli/test/graphql.test.ts) for graphql cli.

Im not sure, i would need to update the graphql config to add a new api definition, but then the other test will also deploy 2 apis

**Review by j33ty — DISMISSED** [review]

**Comment by mwain** [comment]
Rebased on origin/next

**Comment by bobinska-dev** [comment]
Hello @mwain! When will this be released? The customer asked :)

**Review by rexxars — APPROVED** [review]

**Pull request merged**
