### PR TITLE
[form-builder] fix icons not rendred in array insert dropdown menu

### PR DESCRIPTION
**Pull request by vicbergquist**
**Type of change (check at least one)**

- [x]  Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  Documentation (fix or update to documentation)
- [ ]  Maintenance
- [ ]  Other, please describe:

**Does this change require a documentation update? (Check one)**

- [x]  Yes
- [ ]  No

**Current behavior**

The array dropdown menu is missing code that renders type icons. It was supposed to be added in https://github.com/sanity-io/sanity/pull/1958

**Description**

This fixes icons not rendered in array insert dropdown menu 

Screenshot 2020-10-12 at 10 38 52
Screenshot 2020-10-12 at 10 38 45

**Note for release**

- Fixed an issue with icons not rendering in array insert dropdown menu

**Checklist** 

- [x]  I have read the [Contributing Guidelines](https://github.com/sanity-io/sanity/blob/next/CONTRIBUTING.md)
- [x]  The PR title includes a link to the relevant issue
- [x]  The PR title is appropriately formatted: `[some-package] PR title`
- [x]  The code is linted
- [ ]  Corresponding changes to the documentation have been made

### CODE REVIEW

**Comment by vicbergquist** [comment]
@mariuslundgard 👆

**Comment by vicbergquist** [comment]
@rexxars this was supposed to make it into the EX release, but some of the code was missing 🙉 So this fixes it again

**Comment by vicbergquist** [comment]
@mariuslundgard

**Review by skogsmaskin — APPROVED** [review]
Great!

**Pull request merged**
