### PR TITLE
[schema] Fix block annotation validation not handling certain objects

### PR DESCRIPTION
**Pull request by rexxars**
In certain cases, it seems `jsonType` is not returned when validating the schema types. For instance, when using the color schema type as a block annotation, `type` is returned as `object`, but `jsonType` is not present. Maybe @bjoerge has some insight on whether this approach is wrong in the  first place.

Example:
```js
export default {
  name: 'pageBody',
  title: 'Page body',
  type: 'array',
  of: [
    {
      type: 'block',
      marks: {
        annotations: [
          {
            name: 'link',
            title: 'URL',
            type: 'object',
            fields: [
              {
                title: 'URL',
                name: 'href',
                type: 'url'
              }
            ]
          },
          {name: 'color', title: 'Color', type: 'color'}
        ]
      }
    },
    {type: 'image'},
    {type: 'callToAction'},
    {type: 'placeholder'}
  ]
}
```

### CODE REVIEW

**Comment by bjoerge** [comment]
The fact that there's no `jsonType` here sounds to me like the block annotation types aren't getting compiled properly, so what you get back is probably the raw schema definitions, is that right?

**Comment by skogsmaskin** [comment]
It should just ignore `jsonType` here all together. Just check on type. This is run before the schema is proplery compiled. It will get `jsonType` when validated and then compiled.

**Comment by skogsmaskin** [comment]
Forget what I said, inline defined objects will have `type: 'type'` here.

**Comment by bjoerge** [comment]
I totally missed the context here - so since this in the schema validation step (I somehow managed to perceive the context as form builder _validation_)

Pushed a fix for this that figures out jsontype through the parent type chain (the validation type traversal works somewhat different than the regular schema traversal/parsing, and the jsonType is not "inherited" here, but only exists on the root type).

**Pull request merged**
