### PR TITLE
[form-builder] Add OpenStreetmap/leaflet based geopoint input

### PR DESCRIPTION
**Pull request by bjoerge**
I don't think we should enable this by default as it drags in leaflet which is quite heavy, and loads external css, but it may be useful for some.

### CODE REVIEW

**Comment by rexxars** [comment]
Cool! Maybe add a comment or somehow link to https://operations.osmfoundation.org/policies/tiles/ ?

**Comment by rexxars** [comment]
How do we progress this PR? Merge it? Move it to an external plugin?

**Comment by skogsmaskin** [comment]
+1

**Comment by kmelve** [comment]
I think it makes sense to move it to an external plugin

**Comment by rexxars** [comment]
Closing this for now since it's quite old and hasn't seen any updates.
There's also [sanity-plugin-leaflet-input](https://github.com/rexxars/sanity-plugin-leaflet-input) which supports OpenStreetMaps.

**Pull request closed without merging**
