### PR TITLE
Show incoming references

### PR DESCRIPTION
**Pull request by bjoerge**
This needs more work on the visual part, but provides us with building blocks + an example for displaying the documents that have references to the document being edited.

### CODE REVIEW

**Comment by kmelve** [comment]
Just a thought. Should it be possible to configure the title/description for the element? 

For example, let’s say you use references to make a hierarchal content structure. Then it would be useful to be able to contextualize the incoming references as “parent documents”.

**Comment by readeral** [comment]
This is looking rad

**Comment by readeral** [comment]
Hey @bjoerge - anything I can do to help test this/push it along?

I'm going to have a play with your changes in a branch of a project I'm currently working on, but don't really know what's next for this to know how to contribute.

**Comment by kmelve** [comment]
@readeral We're considering creating some new better primitives for stuff like this. I believe the best thing, for now, is to stay tuned :)

**Comment by EivindGelato** [comment]
Would love to have this feature... Any ETA on merge?

**Comment by readeral** [comment]
Just dropping by to say I'm still tuned ;-P

**Comment by pawelngei** [comment]
This could be a really useful feature!

@bjoerge what do you think about creating a Part for the visuals of the IncomingLinks instead of adding it straight to FormView? This way it'd be easier pluggable / configurable.

**Comment by rexxars** [comment]
There's a plugin now that provides a pretty good and customizable implementation of this feature: https://www.sanity.io/plugins/documents-pane

We _might_ revisit this officially later, but for now we'd recommend people use that!

**Pull request closed without merging**
