### PR TITLE
fix(core): add scrolling to workspace login screen 

### PR DESCRIPTION
**Pull request by ninaandal**
### Description
Added scrolling to the list of workspaces on the login screen. 
image

### What to review
That the login screen can be scrolled. 

### Notes for release
Fixes issue with scrolling of workspaces on login screen

### CODE REVIEW

**Comment by binoy14** [comment]
Any way to test this? I am not sure how to get to this page? 😬

**Comment by robinpyon** [comment]
> Any way to test this? I am not sure how to get to this page? 😬

Open the preview link in an incognito link, then click the 'Choose another workspace' button

**Review by binoy14 — APPROVED** [review]
LGTM! Thanks!

**Review by robinpyon — APPROVED** [review]
Thank you @ninaandal!

**Pull request merged**
